29/feat/MyFolderAreaLogIn 컴포넌트 구현
prgrms-web-devcourse/Team-03-LinkBook-FE pull request #39
Opened 2022-07-31 08:49 UTC by Miral3

### 📌 설명
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59829606/182018031-73f8a1e2-ac87-4d13-95d7-71cd98f4cd01.png">

### 🎨 구현 내용
* 로그인 되었을 때 보여질 나의 폴더 리스트를 구현했습니다.
* 캐러셀을 이용해 자신이 메인에 보고싶은 폴더 리스트를 렌더링 합니다. 
  * 데이터가 3개 이하이면 그냥 중앙에 렌더링 합니다.

### ✅ 중점적으로 봐줬으면 하는 부분
* 카테고리 컴포넌트가 현재 수정중이기 때문에 아직 메인 페이지에는 렌더링 하지 않았습니다.
* tags가 단순한 string 배열이기 때문에 Tag 컴포넌트의 tagItems의 타입을 수정했습니다.
* 캐러셀을 집중적으로 리뷰해주셨으면 좋겠습니다.
### 🚀 연관된 이슈
closes #29

2022-07-31 12:46 UTC, Jungjjeong requested changes
용상님 구현 내용 확인했습니다. 코드가 깔끔하네요. 🤗 
또한 반응형도 잘 구현하셨네요. 5개 출력, 3개 출력, 1개 출력 모두 다 잘 작동합니다. 이슈 해결 후 바로 머지하시면 될 것 같습니다. 

- 반응형+인덱스 관련 이슈가 있습니다. 확인 부탁드립니다.

2022-07-31 12:46 UTC, Jungjjeong commented on web/pages/components/FolderSlider/FolderSlider.style.ts
> +`;
용상님 PR 설명과 다르게 저는 버튼 위치가 이렇습니다. 혹시 의도하신건지 궁금합니다!
![image](https://user-images.githubusercontent.com/72294509/182026437-b3fbc825-7a9d-4bdb-924a-a53744d4cda5.png)
8%가 아닌 다른 값을 찾아야 할 것 같습니다.

2022-07-31 12:46 UTC, Jungjjeong commented on web/pages/components/FolderSlider/FolderSlider.tsx
> +export default FolderSlider;
## 버그 리포트

UI의 너비를 줄이고 카드가 마지막 인덱스일경우, 다시 너비를 늘리면 인덱스가 다시 처음 카드로 돌아가지 않는 이슈가 있습니다. 
![image](https://user-images.githubusercontent.com/72294509/182026704-33d824be-7552-4bfb-b227-b62b837bdd4e.png)

또한 이 상태에서 인덱스가 무한으로 증가합니다. 
![image](https://user-images.githubusercontent.com/72294509/182026798-7fe608e5-2b25-4d43-b3ef-892bcb4764ab.png)

확인 부탁드립니다!

2022-08-01 03:56 UTC, Miral3 commented on web/pages/components/FolderSlider/FolderSlider.style.ts
> +`;
아 디스플레이마다 width가 달라서 그런가 보네요 수정하겠습니다.

2022-08-01 07:01 UTC, Miral3 commented on web/pages/components/FolderSlider/FolderSlider.tsx
> +export default FolderSlider;
윈도우 사이즈에 따라 로직을 추가해서 해결했습니다.

2022-08-01 07:08 UTC, Jungjjeong approved these changes
이슈 해결 확인했습니다.

2022-08-01 07:11 UTC, merged